default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: ""
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: demostruck2

test:
  <<: *default
  database: demostruck2_test

production:
  <<: *default
  database: demostruck2_production
  username: demostruck2
  password: <%= ENV['LOGIN_APP_DATABASE_PASSWORD'] %>